### ISSUE TITLE
Getting error when installing Nuget package

### ISSUE THREAD

**Issue by supershopping** [marcojak/MauiMTAdmob#1]
Hi,

I am getting below error when installing this nuget package. Did I miss anything here? How to resolve? Thanks,

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'C:\Users\XXXX\.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\net6.0-ios15.4\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\Headers\GoogleUtilitiesComponents-umbrella.h'.

**Comment by JeroenMBooij** [comment]
@supershopping this is because the path is too long. I am assuming you don't use Windows Pro or don't have long path enabled. Check out this comment and the referenced issue: [https://github.com/marcojak/MTAdmob/issues/102#issuecomment-1193099575](https://github.com/marcojak/MTAdmob/issues/102#issuecomment-1193099575)

**Comment by marcojak** [comment]
As this is not linked to the plugin but the configuration on the user's machine, I'm closing the issue.

**Comment by jfversluis** [comment]
I have the same error and long paths is enabled...

**Comment by marcojak** [comment]
I've solved this changing my NUGET_PACAKGES path. (to c:\nugets).

**Comment by marcojak** [comment]
I fixed this issue on my machine following with comment: https://github.com/xamarin/GoogleApisForiOSComponents/issues/555#issuecomment-1145943195

**Comment by marcelbeeker** [comment]
Execute dotnet add packages <name of projectfile> package Plugin.MauiMTAdmob from the command prompt solved this issue on my system

**Comment by jfversluis** [comment]
@leowagnersouza see the comment right above you, if you install it through the command-line it does work.

**Comment by JamesHalldorsson** [comment]
Here is how I fixed the problem, it's a combination of some of the aforementioned methods.

firstly go into your registry editor, run as an administrator navigate to this path Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem

change the LONGPATHSENABLED to 1 (true) and save changes.

Reset your computer

once you have reset, go to the Developer Command Prompt for visual studio.

Change directory to the directory containing your .csproj file with the command cd /d and then followed by the path

once you are in this directory, execute the command: dotnet add package Plugin.MauiMTAdmob --version 1.0.4

If you follow these steps in sequence, this should install the package.
