### ISSUE TITLE
include dotnet8.0 in TargetFrameworks

### ISSUE THREAD

**Issue by Th3L0x** [marcojak/MauiMTAdmob#108]
Could you include dotnet8.0? Because if somebody wants use xUnitTest while this package is installed the package restore will fail.
(only android, ios, maccatalyst and windows are included)

**Comment by marcojak** [comment]
.net8 is already included in all platforms. Make sure everything is updated
and it will work.

**Comment by Th3L0x** [comment]
![2](https://github.com/user-attachments/assets/65872bd6-45d4-4af6-8f60-61f54fe79eeb)
![3](https://github.com/user-attachments/assets/bed8c765-531f-46a8-8a19-80992c568086)
![1](https://github.com/user-attachments/assets/732604a8-79c8-4b3f-b399-12b1d82287ec)


I mean pure dotnet8.0, unfortunately this is a must for xUnit Test type project

**Comment by marcojak** [comment]
Oh I see.
I'll add it and do some tests and if all works fine, I'll release it asap.

**Comment by Th3L0x** [comment]
Thank you!

**Comment by Th3L0x** [comment]
Hey, do you have any news on this?:)

**Comment by marcojak** [comment]
I'll add it to the next version which should be online by mid-next week.

**Comment by marcojak** [comment]
I've just released version 1.7.1 which includes it.
Closing as completed.
