### ISSUE TITLE
winui exception...

### ISSUE THREAD

**Issue by blackshining** [marcojak/MauiMTAdmob#11]
Microsoft.Maui.Platform.HandlerNotFoundException
  HResult=0x80131500
  메시지=Handler not found for view Plugin.MauiMTAdmob.Controls.MTAdView.
  소스=Microsoft.Maui
  StackTrace:
   / Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   / Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   / Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   / Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   / Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   / Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   / Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   / Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   / Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   / Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   / Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   / Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   / Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   / Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   / Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   / Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   / Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
   / Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   / Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   / Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   / Microsoft.Maui.Controls.Application.set_MainPage(Page value)
   / TranslateLab.Views.Componnent.LoadingView.<Check>d__5.MoveNext() 파일

**Comment by marcojak** [comment]
I think the reason is that the plugin doesn't support WinUI but of course the app shouldn't crash.
If that's the case, I'll fix it and release a new version asap.

**Comment by marcojak** [comment]
I've just published version 1.0.2 that should allow you to use the plugin on Windows with no compatibility problems (no ads on Windows yet).
Let me know if it works!

**Comment by blackshining** [comment]
7.0.... i'm don't use... 7.0 that very error...

**Comment by marcojak** [comment]
The new version should not cause any errors on WinUI
