### ISSUE TITLE
LoadInterstitial method loads ad only once

### ISSUE THREAD

**Issue by nightBaker** [marcojak/MauiMTAdmob#13]
I use `CrossMauiMTAdmob.Current.LoadInterstitial(interstitialsAdId);` to load interstitial and show it if it is ready.
First time, everything works.
But if I want to load ad second time it will never be loaded.
I subscribe for `OnInterstitialLoaded` (never called)  or check `CrossMauiMTAdmob.Current.IsInterstitialLoaded()` (always false)

**Comment by marcojak** [comment]
I've just published version 1.0.2 that should solve this issue.
