### ISSUE TITLE
Tutorial page is offline

### ISSUE THREAD

**Issue by rodrigopiccelli** [marcojak/MauiMTAdmob#14]
Sorry for using the issues page to report this but the page where the tutorial was hosted has been offline for a few days.

**Comment by marcojak** [comment]
Hi Rodrigo.
Thank you for letting me know. I wasn't aware of the problems with XamarinExpert and MauiExpert.
Problems with the hosting provider. It's all solved now and the websites and the guides are available again.

Closing this issue.
