### ISSUE TITLE
Getting Null Reference inside package when displaying banner ads

### ISSUE THREAD

**Issue by RobertWildgoose** [marcojak/MauiMTAdmob#16]
Hey, 
I've followed the set-up docs and everything appears correctly set up.

I'm using my own App ID and Banner ID
Added a banner to the middle of my page and upon running i get a null exception.

Seems to be something to do with the AdSizeConstraint.

I've included logs, any chance you could help me work out the issue?

Added Xaml incase this helps
```
<controls:MTAdView
                AdSize="Banner"
                AdsId="ca-app-pub-xxxxxxxxxxxxx"
                x:Name="myAds"></controls:MTAdView>
```

[stack.txt](https://github.com/marcojak/MauiMTAdmob/files/10216997/stack.txt)

Its going to be something simple that im missing.

**Comment by RobertWildgoose** [comment]
Resolved, 
For anyone who may fall into a similar issue, the applicationID is casesensitive.

**Comment by DeerSteak** [comment]
Do you mean the GADApplicationIdentifier in Info.plist or something else? I'm having the same problem.
