### ISSUE TITLE
version 1.0.2 does not work on maui

### ISSUE THREAD

**Issue by pablouix** [marcojak/MauiMTAdmob#18]
It won't let me install this version in the project, check it out. With the first version if it is installed but it does not work for me.\

![image](https://user-images.githubusercontent.com/97201832/209449337-e1b3ca50-0ac6-496b-871a-97fd609a402c.png)

**Comment by pablouix** [comment]
"It won't let me install this version in the project, look. With the first version it installs but it doesn't work for me."

I was working on the project on net 6, after switching to net 7 it works

![image](https://user-images.githubusercontent.com/97201832/209455474-8b0559fe-ea8f-4168-9ead-c3975df55893.png)

**Comment by MdLejTeCole** [comment]
I also couldn't install this Nuget.
Error Could not find a part of the path 'C:\Users\vivek.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\xamarinios10\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\PrivateHeaders\GULCCComponentContainerInternal.h'.

It is connected with path length. If your error is the same solution is there: https://github.com/xamarin/GoogleApisForiOSComponents/issues/555

**Comment by Znow** [comment]
@marcojak ?

**Comment by marcojak** [comment]
Have you tried the latest version of the plugin? Let me know if that works for you.
