### ISSUE TITLE
CrossMauiMTAdmob.Current.LoadRewarded, Only work One time.

### ISSUE THREAD

**Issue by TripHere** [marcojak/MauiMTAdmob#21]
After loading the advertisement through LoadRewarded, 
ShowRewarded Reward Ads appears on the screen. 
But ShowRewarded again, 
the advertisement will not be exposed, 
also  LoadRewarded again and ShowRewarded, Not working this function.

**Comment by nicolajhansen97** [comment]
Yes, seems to only occurs on IOS as Martinedo says. Not sure it's a directly problem with this plugin tho. After researching it seems like alot of people have problems with this even without this plugin but with AdMob.

**Comment by iancona** [comment]
Same here. If you close the app and re-launch it then again it will show but only first time. Is there some way to reset the request, as it happens with an app re-launch?

**Comment by marcojak** [comment]
Fixed in version 1.3.3
