### ISSUE TITLE
The type 'ConsentDebugSettings' already contains a definition for 'DebugGeography'

### ISSUE THREAD

**Issue by brimbon** [marcojak/MauiMTAdmob#23]
Whenever I put the .aar file as android library it throws this exception:
The type 'ConsentDebugSettings' already contains a definition for 'DebugGeography' AdMobTest (net7.0-android)	
C:\Users\lamin\OneDrive\Visual Studio\MAUI\AdMobTest\obj\Debug\net7.0-android\generated\src\Com.Google.Android.Ump.ConsentDebugSettings.cs

**Comment by marcojak** [comment]
Try the latest version. It already contains the code for the Consent
