### ISSUE TITLE
Uninstalling plugin errors

### ISSUE THREAD

**Issue by fpaezf** [marcojak/MauiMTAdmob#25]
Installed the nuget package to test, now after remove the nuget package getting an error:

Java.Lang.RuntimeException: 'Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

How to step back?

**Comment by fpaezf** [comment]
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.InfinitySoftware.Aparcator, PID: 2299
[AndroidRuntime] java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
[AndroidRuntime] 
[AndroidRuntime] ******************************************************************************
[AndroidRuntime] * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
[AndroidRuntime] * should follow the instructions here:                                       *
[AndroidRuntime] * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
[AndroidRuntime] * to add a valid App ID inside the AndroidManifest.                          *
[AndroidRuntime] * Google Ad Manager publishers should follow instructions here:              *
[AndroidRuntime] * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
[AndroidRuntime] ******************************************************************************
[AndroidRuntime] 
[AndroidRuntime] 
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:8313)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7810)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7564)
[AndroidRuntime] 	at android.app.ActivityThread.access$1700(ActivityThread.java:315)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:226)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:313)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8751)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
[AndroidRuntime] Caused by: java.lang.IllegalStateException: 
[AndroidRuntime] 
[AndroidRuntime] ******************************************************************************
[AndroidRuntime] * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
[AndroidRuntime] * should follow the instructions here:                                       *
[AndroidRuntime] * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
[AndroidRuntime] * to add a valid App ID inside the AndroidManifest.                          *
[AndroidRuntime] * Google Ad Manager publishers should follow instructions here:              *
[AndroidRuntime] * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
[AndroidRuntime] ******************************************************************************
[AndroidRuntime] 
[AndroidRuntime] 
[AndroidRuntime] 	at com.google.android.gms.ads.internal.client.zzee.attachInfo(com.google.android.gms:play-services-ads-lite@@21.2.0:20)
[AndroidRuntime] 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@21.2.0:1)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:8308)
[AndroidRuntime] 	... 11 more

**Comment by fpaezf** [comment]
Removed the "<meta-data" line from androidmanifest but same problem.

**Comment by MarcosCostaDev** [comment]
you need to add these [metadata ](https://developers.google.com/admob/android/quick-start#import_the_mobile_ads_sdk) in your `Platforms/Android/MainApplication.cs`

Google documentation talk about these elements to place in the manifest:
```xml
<manifest>
    <application>
        <!-- Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713 -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
    </application>
</manifest>
```

However, you can use the MAUI approach for that, like the example below:

```csharp
    [Application]
    [MetaData("com.google.android.gms.ads.AD_MANAGER_APP", Value = "true")]
    [MetaData("com.google.android.gms.ads.APPLICATION_ID", Value = "ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy")]
    public class MainApplication : MauiApplication
    {
        public MainApplication(IntPtr handle, JniHandleOwnership ownership)
            : base(handle, ownership)
        {
        }

        protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();
    }
}
```
