### ISSUE TITLE
Local module descriptor class for com.google.android.gms.ads.dynamite not found

### ISSUE THREAD

**Issue by JeroenMBooij** [marcojak/MauiMTAdmob#3]
When trying to load an interstitial ad I get an error saying `Local module descriptor class for com.google.android.gms.ads.dynamite not found`

The full stacktrace:
`[Ads] Failed to instantiate ClientApi class.
[DynamiteModule] Local module descriptor class for com.google.android.gms.ads.dynamite not found.
[DynamiteModule] Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:221908400
[DynamiteModule] Selected remote version of com.google.android.gms.ads.dynamite, version >= 221908400
[DynamitePackage] Instantiated singleton DynamitePackage.
[DynamitePackage] Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[Ads] This request is sent from a test device.
[ConnectionStatusConfig] Dynamic lookup for intent failed for action: com.google.android.gms.leibniz.events.service.START
[GmsClient] unable to connect to service: com.google.android.gms.leibniz.events.service.START on com.google.android.gms
[WebViewFactory] Loading com.google.android.webview version 83.0.4103.106 (code 410410686)
[anyname.routin] The ClassLoaderContext is a special shared library.
[nativeloader] classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86_64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86_64:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86_64:/product/lib64:/system/product/lib64
[anyname.routin] The ClassLoaderContext is a special shared library.
[nativeloader] classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86_64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86_64:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86_64:/product/lib64:/system/product/lib64
[cr_LibraryLoader] Loaded native library version number "83.0.4103.106"
[cr_CachingUmaRecorder] Flushed 3 samples from 3 histograms.
[DynamiteModule] Local module descriptor class for com.google.android.gms.ads.dynamite not found.
[Ads] Invoke Firebase method getInstance error.
[Ads] The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firebase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date
[DynamiteModule] Local module descriptor class for com.google.android.gms.ads.dynamite not found.`

**Comment by marcojak** [comment]
Try the sample project. It works for sure.
I can tell you I've seen those warning messages also in the version for
Xamarin but they don't cause any issues.

If you don't see interstitials it's probably something else, probably
something related to the ads IDs. Make sure you are using the test IDs and
add your phone id to the test devices list.

**Comment by JeroenMBooij** [comment]
My bad I was only using the test ID for the banner and not for the interstitial 🤦
