### ISSUE TITLE
How to use it on blazor hybrid maui?

### ISSUE THREAD

**Issue by gandensang** [marcojak/MauiMTAdmob#33]
its posible to use it in blazor hybrid maui ?

**Comment by Kebechet** [comment]
Depends on the ad type:
- if it is banner than you have to specify it in MainPage.xaml (above or under BlazorWebView)
- if it is Rewarded, you can trigger it by wrapping it's functionality to some service

**Comment by marcojak** [comment]
Close as @Kebechet correctly answers the question
