### ISSUE TITLE
Ads do not show in Maui after last Maui update

### ISSUE THREAD

**Issue by pgmariotti** [marcojak/MauiMTAdmob#35]
Since the last update of Visual Studio to version 17.6.2 an app I am developing stubbornly refuses to show AdMob ads.
I have set an event handler for the ad loading on android, and checked that the ad s do not load at all.
The ad I am trying to load is the standard Google banner test ad ca-app-pub-3940256099942544/6300978111.

**Comment by manusoft** [comment]
Me also same problem, after updating vs2022 to 17.6.2 ads not showing.

[reenguardfinde] Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[Ads] Ad failed to load : 3

**Comment by erossini** [comment]
Same issue here

**Comment by marcojak** [comment]
I'm going to close this issue ad it's not an issue but just in case someone else sees this:
Ad failed to load : 3 means that everything works fine just there are no ads to show.
Exactly the error is: "ad request was successful but there are no ads to be served."
