### ISSUE TITLE
Google consent management

### ISSUE THREAD

**Issue by FrankPohl** [marcojak/MauiMTAdmob#36]
Hi,
I'm using your component and am really confident with it. But now Google has announced this:
"Later this year, Google will require all publishers serving ads to EEA and UK users to use a Google-certified Consent Management Platform (CMP). You can use any [Google-certified CMP ](https://support.google.com/admob/answer/13554116)for this purpose, including Google's own consent management solution. If you are interested in using Google's consent management solution, start by setting up your GDPR message and implementing the [UMP SDK](https://support.google.com/admob/answer/10113005). [Learn more](https://support.google.com/admob/answer/10113207).

So my question is: Are you going to support this in a future version of the component?
Kind regards 
Frank

**Comment by marcojak** [comment]
Yes, this is now supported.
