### ISSUE TITLE
 android 33 not working

### ISSUE THREAD

**Issue by pablouix** [marcojak/MauiMTAdmob#38]
in android 33 it doesn't work for me, in a previous version yes.

here I show photos
![image](https://github.com/marcojak/MauiMTAdmob/assets/97201832/49e6efe5-1b0a-4289-861f-73f4ddd18f52)
![image](https://github.com/marcojak/MauiMTAdmob/assets/97201832/aeebfb19-e8df-43dd-8a68-66bc0233cb4e)
![image](https://github.com/marcojak/MauiMTAdmob/assets/97201832/08e6c04b-b57c-4b76-9419-cf7139580411)

**Comment by marcojak** [comment]
Try the latest version.
It should work
