### ISSUE TITLE
System.NotImplementedException has been thrown (LoadInterstitial)

### ISSUE THREAD

**Issue by ablohme86** [marcojak/MauiMTAdmob#43]
<img width="1064" alt="Screenshot 2023-11-05 at 15 48 54" src="https://github.com/marcojak/MauiMTAdmob/assets/17109732/84a38830-93a6-4642-9237-0062ed288d5d">

**Comment by marcojak** [comment]
It seems the plugin is not correctly installed.

Try the latest version and see if it works for you.
