### ISSUE TITLE
Project doesn't build with MauiMTAdmob

### ISSUE THREAD

**Issue by prok155** [marcojak/MauiMTAdmob#46]
When I add MauiMTAdmob package to my application and try to build it on iOS, project doesn't build and I can see following error in visual studio:

`File 'C:/Users/username/AppData/Local/XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/GoogleMobileAds' is not a valid framework: Index and count must refer to a location within the buffer.`

### Affected platforms

iOS

### Affected platform versions

.net MAUI 8.0.3
Xcode 15.1

**Comment by marcojak** [comment]
Hi.
I think the issue might be related to a path too long. Try to move the directory to a shorter one. 
For example: c:/n
This might solve the issue

**Comment by marcojak** [comment]
Hi,
I've released version 1.1.1 and this might be not relevant anymore, if you still experience this issue with the new version, feel free to reopen the issue
