### ISSUE TITLE
Display only the first adv

### ISSUE THREAD

**Issue by erossini** [marcojak/MauiMTAdmob#49]
Hi,
I have my MAUI app with NET8. The plugin is working but the advs are not displayed after the first adv is displayed.

I have to close the app and reopen it to see another advertisement.

Basically, I want to display a rewarding advertisement after a user activity. Between one activity and another could pass a few minutes.

Do you know if this is a common issue?

Thank you in advance,
Enrico

**Comment by marcojak** [comment]
I think this is fixed in version 1.3.3
