### ISSUE TITLE
Getting an error while installing MauiMTAdmob

### ISSUE THREAD

**Issue by NikolayIT** [marcojak/MauiMTAdmob#5]
I am getting the following error while installing the `MauiMTAdmob` NuGet package:

```
'C:\Users\Nikolay.IT\.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\xamarinios10\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\Headers\GoogleUtilitiesComponents-umbrella.h'.				
```

**Comment by marcojak** [comment]
Hi.
Have a look at this:
https://github.com/marcojak/MauiMTAdmob/issues/1

The problems is not with the library itself, but with that nuget package (path too long).

**Comment by marcojak** [comment]
In particular.
You can solve this issue reading this: https://github.com/xamarin/GoogleApisForiOSComponents/issues/555#issuecomment-1145943195
