### ISSUE TITLE
Advertising on Windows and macOS

### ISSUE THREAD

**Issue by erossini** [marcojak/MauiMTAdmob#50]
This is an open question. Is this plugin has some solution to display advertisements on Windows and macOS?

Is there any provider that offers an SDK for MAUI to display advertisements for this platforms?

Thank you in advance,
Enrico

**Comment by marcojak** [comment]
I will investigate this.
Closing it as it's not an issue but feel free to open it as a discussion so more people can contribute and offer an opinion
