### ISSUE TITLE
The "AndroidFixManifests" parameter is not supported by the "XamarinDownloadArchives"

### ISSUE THREAD

**Issue by PrzemekZA** [marcojak/MauiMTAdmob#54]
Hi,

After Install Plugin.MauiMTAdmob (1.0.4) I have got an errors:

1. Error	MSB4064	The "AndroidFixManifests" parameter is not supported by the "XamarinDownloadArchives" task loaded from assembly: Xamarin.Build.Download, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from the path: C:\Nugets\xamarin.build.download\0.11.4\buildTransitive\Xamarin.Build.Download.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.	MyProjectMAUI	C:\Nugets\xamarin.build.download\0.11.0\buildTransitive\Xamarin.Build.Download.targets	60	
2. 
3. Error	MSB4063	The "XamarinDownloadArchives" task could not be initialized with its input parameters. 	MyProjectMAUI	C:\Nugets\xamarin.build.download\0.11.0\buildTransitive\Xamarin.Build.Download.targets	52	

.net7 and .net8

App can be Compiled, Run and Deploy on Android with this errors. iOS not tested yet.

**Comment by JhowDevBR** [comment]
up

**Comment by marcojak** [comment]
I'm currently investigating the issue to see if it's still present in the new version 1.1.0 just released and I'll fix if a fix is still required

**Comment by marcojak** [comment]
If meanwhile, you have a quick way to replicate the issue, let me know as it will help me to identify and fix the issue

**Comment by PrzemekZA** [comment]
Steps:
1. Create new MAUI project in VS 
2. Add plugin from Nuget
3. Build or Publish

**Comment by marcojak** [comment]
Ok, the issue belongs to Xamarin.Build.Download (usually when multiple versions of the plugin are used).
I've just released version 1.1.1 of the plugin including that package by default.

It should fix the issue now.

Let me know.
