### ISSUE TITLE
App Crashing on iOS at start up, release build only.

### ISSUE THREAD

**Issue by sachinkanadia** [marcojak/MauiMTAdmob#55]
App Crashing on iOS at start up, release build only.

I have ensured that I have added the following values correctly to the info.plist:
GADApplicationIdentifier
GADIsAdManagerApp

When I remove the reference to the MauiMTAdmob package it works fine.

Please could someone advise?

Many Thanks.

**Comment by marcojak** [comment]
Please try the latest version (1.2.0) and let me know if you are still experiencing the issue

**Comment by sachinkanadia** [comment]
[LightWork-2024-02-08-115853 copy.ips.txt](https://github.com/marcojak/MauiMTAdmob/files/14230318/LightWork-2024-02-08-115853.copy.ips.txt)

Please find the crash report. It's still crashing after upgrading to the latest Nuget package - 1.2.1.

If you could give a few pointers that would be a great help.

Thanks
