### ISSUE TITLE
Version 1.1.1 and iOS

### ISSUE THREAD

**Issue by erossini** [marcojak/MauiMTAdmob#59]
Sorry to bother you again. For iOS, I wrote this code

```
[Register("AppDelegate")]
public class AppDelegate : MauiUIApplicationDelegate
{
    protected override MauiApp CreateMauiApp()
    {
        raw.SetProvider(new SQLite3Provider_sqlite3());
        return MauiProgram.CreateMauiApp();
    }

    public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {
        CrossMauiMTAdmob.Current.Init(Constants.MauiMTAdmobLicence);
        MobileAds.SharedInstance.Start(CompletionHandler);
        return base.FinishedLaunching(application, launchOptions);
    }

    private void CompletionHandler(InitializationStatus status) { }
}
```

Do I still need the `MobileAds` or can I remove it?

**Comment by marcojak** [comment]
No problem,

Remove it, also on iOS, the plugin will automatically call it.

**Comment by erossini** [comment]
I'm not sure if this issue is related to this component. The error I get is

> ld: warning: object file
> (/Users/enrico/Library/Caches/Xamarin/mtbs/builds/LanguageInUse/1fa03704bb15e35c6f47a701d9d92131e3e0740198296a93338bb3c829bc9cf7/C:/Users/enric/AppData/Local/XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator/GoogleMobileAds.framework/GoogleMobileAds(GADGestureMock.o))
> was built for newer iOS Simulator version (14.5) than being linked
> (14.0) ld: warning: object file
> (/Users/enrico/Library/Caches/Xamarin/mtbs/builds/LanguageInUse/1fa03704bb15e35c6f47a701d9d92131e3e0740198296a93338bb3c829bc9cf7/C:/Users/enric/AppData/Local/XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator/GoogleMobileAds.framework/GoogleMobileAds(GADGestureRecognizerMock.o))
> was built for newer iOS Simulator version (14.5) than being linked
> (14.0) ld: in
> /Users/enrico/Library/Caches/Xamarin/mtbs/builds/LanguageInUse/1fa03704bb15e35c6f47a701d9d92131e3	LanguageInUse	C:\Program
> Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets	1559

**Comment by marcojak** [comment]
Is it a warning or an error?
It seems an issue with the deployment target.
Try to change it and see if it removes the warnings.

**Comment by erossini** [comment]
This is an error

![image](https://github.com/marcojak/MauiMTAdmob/assets/9497415/944b0bc4-1d43-49de-8954-c779cfebd6d3)

I tried to change the deployment target

![image](https://github.com/marcojak/MauiMTAdmob/assets/9497415/8bccb6a7-6fb4-48b0-a9da-dbc55f348c7e)

and in the project settings

![image](https://github.com/marcojak/MauiMTAdmob/assets/9497415/2ceecab9-ab54-4882-8e27-33ba7440e24a)

**Comment by marcojak** [comment]
I've just tried on my PC + Mac and it worked fine.
The simulator I've tried it on is iPhone 15 with iOS 17.2.

I've just updated the sample code on this repository. Does it work for you?
I suspect that that version of iOS might be too old.
