### ISSUE TITLE
App Crashing on iOS at start up, release build only.

### ISSUE THREAD

**Issue by sachinkanadia** [marcojak/MauiMTAdmob#65]
[LightWork-2024-02-08-115853 copy.ips.txt](https://github.com/marcojak/MauiMTAdmob/files/14230319/LightWork-2024-02-08-115853.copy.ips.txt)

Rename the attachment to ".ips" only.

After upgrading to the latest version 1.2.1 its still crashing on release build for iOS. Debug build runs fine.

If you could help that would be much appreciated.

Thanks

**Comment by marcojak** [comment]
Could you try to change the "Linker behaviour" to "Don't Link"?
So we cna see if it works with that.

**Comment by sachinkanadia** [comment]
[2024-02-10_19-27-56.0078_+0000-00f9e044e2c066f1ac7dac99b3980c0e7523ab25.crash.txt](https://github.com/marcojak/MauiMTAdmob/files/14230412/2024-02-10_19-27-56.0078_%2B0000-00f9e044e2c066f1ac7dac99b3980c0e7523ab25.crash.txt)

This is the symbolical crash report. I will try to turn off the Linker.

**Comment by sachinkanadia** [comment]
I tried turning off the Linker however it throws more errors when I try to upload to TestFlight.
So then I tried turning the Linker back on and using another AppId for the GADApplicationIdentifier (The test AppId in the readme file). The App is still crashing in the same place on start-up.

**Comment by marcojak** [comment]
I'll try to build it in release and see if I get the same issue

**Comment by sachinkanadia-se** [comment]
The release build will run fine. It's only when I run the App from TestFlight I get the error on start up. If you could try to replicate and see that would be great. Thanks

**Comment by marcojak** [comment]
I haven't had a chance to test the release on TestFlight.

Are you sure the issue on TestFlight comes from this plugin? Have you tried on TestFlight a test version without the plugin?

**Comment by jb11-repo** [comment]
Hi @marcojak I'm also having this issue where it crashes after pushing to TestFlight (I see the splash screen before it crashes). iOS simulator is fine. I previously pushed the app without ads to TestFlight and it didn't crash, so I think I have the same issue. Has anyone figured out a fix for this?

**Comment by marcojak** [comment]
Could you try version 1.6.1.

I've done a test yesterday, using version 1.6.1 and publishing the app on Testflight and it worked fine.
Could you check if it works for you?

**Comment by sachinkanadia** [comment]
Hey Marco,

This wasn’t an issue to do with your package. It’s been resolved. Please close. Thanks mate.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
