### ISSUE TITLE
Package not installing

### ISSUE THREAD

**Issue by tanakamawere** [marcojak/MauiMTAdmob#7]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'C:\Users\user\.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\xamarinios10\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\PrivateHeaders\GULCCComponentContainerInternal.h'.				

The error is above.

**Comment by eyeveye** [comment]
> Severity Code Description Project File Line Suppression State Error Could not find a part of the path 'C:\Users\user.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\xamarinios10\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\PrivateHeaders\GULCCComponentContainerInternal.h'.
> 
> The error is above.

Refer to this: https://github.com/xamarin/GoogleApisForiOSComponents/issues/555#issuecomment-1145943195
