### ISSUE TITLE
Advertisement not visible - MAUI Android app

### ISSUE THREAD

**Issue by ekontro** [marcojak/MauiMTAdmob#74]
Hi,
I created a test application adding the required entries:

In the MainActivity.cs file:
protected override void OnCreate(Bundle? savedInstanceState)
{
    base.OnCreate(savedInstanceState);
    MobileAds.Initialize(this);
}

In the MainPage.xaml file:
xmlns:controls="clr-namespace:Plugin.MauiMTAdmob.Controls;assembly=Plugin.MauiMTAdmob"

and

<controls:MTAdView x:Name="AdView" AdsId="ca-app-pub-3940256099942544/9214589741" HeightRequest="50" WidthRequest="320" Grid.Row="0" IsVisible="True">

In the AndroidManifest.xaml file:
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-170763......./>

The application starts, but the banner is not visible. What could be the reasons for this?

**Comment by marcojak** [comment]
Hi.

You don't need to initialise the mobile ads, but you need to initialise the
plugin in the platform code.

You can check the sample code to see how to initialise it.

**Comment by ekontro** [comment]
Thank you Marco,
In fact, it was enough to change the initialization code.
Now the test ads are visible for e.g. adsID "ca-app-pub-3940256099942544/9214589741", but when changing to the real banner ID the ad is still not visible. Is it because the application is not approved or connected to the store?

**Comment by marcojak** [comment]
I'm glad it worked.

Correct. Your app needs to be on the store to view the ads. It's also
forbidden to show real ads during tests and Google might suspend or cancel
your account doing this. This is why you should always use test ads Ids or
insert your device id as test device.
Anyway if the test ads work, then the normal ads will work as well.

**Comment by ekontro** [comment]
Thank you very much Marco for your help :)
