### ISSUE TITLE
Issue in Release mode 

### ISSUE THREAD

**Issue by erossini** [marcojak/MauiMTAdmob#79]
I have the version 1.4.2. When I try to deploy in `Release` my application, I get this new error

> clang++ exited with code 1:
> ld: warning: object file (/Users/enrico/Library/Caches/Xamarin/mtbs/builds/LanguageInUse/1fa03704bb15e35c6f47a701d9d92131e3e0740198296a93338bb3c829bc9cf7/C:/Users/enric/AppData/Local/XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator/GoogleMobileAds.framework/GoogleMobileAds(GADGestureMock.o)) was built for newer iOS Simulator version (14.5) than being linked (14.0)
> ld: warning: object file (/Users/enrico/Library/Caches/Xamarin/mtbs/builds/LanguageInUse/1fa03704bb15e35c6f47a701d9d92131e3e0740198296a93338bb3c829bc9cf7/C:/Users/enric/AppData/Local/XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator/GoogleMobileAds.framework/GoogleMobileAds(GADGestureRecognizerMock.o)) was built for newer iOS Simulator version (14.5) than being linked (14.0)
> ld: in /Users/enrico/Library/Caches/Xamarin/mtbs/builds/LanguageInUse/1fa03704bb15e35c6f47a701d9d92131e3	LanguageInUse (net8.0-ios)	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8053\targets\Xamarin.Shared.Sdk.targets

Do you know how to fix it? Do I have to change the `Target iOS version` in the project?

**Comment by marcojak** [comment]
Have you solved the issue?
I think I've seen something similar while working on the new version of the plugin.
You can check the csproj of the .Net 8 sample app to see how I fixed it.
I hope it helps.

**Comment by erossini** [comment]
The issue fixed itself, probably it was something related to the deployment.
Thank you,
Enrico
