### ISSUE TITLE
Current.Init parameters

### ISSUE THREAD

**Issue by Kebechet** [marcojak/MauiMTAdmob#81]
In the call:
`CrossMauiMTAdmob.Current.Init(this,"<app id>");`

does the `appId` represent the same value like the one written in the manifest ?
If so, can you please also mention it in the [docs](https://hightouchinnovation.com/MMTAdmobGuide) ?

Related to: https://github.com/marcojak/MauiMTAdmob/issues/73

**Comment by marcojak** [comment]
Sorry to answer just now.

Yes it's the same value.
I'll definitely add it to the docs!

**Comment by marcojak** [comment]
I've updated the docs.
Closing for now.
Any issues, let me know.
