### ISSUE TITLE
IOS Simulator not compiling latest version

### ISSUE THREAD

**Issue by whann0205** [marcojak/MauiMTAdmob#84]
Maybe somebody can point me in the right direction.
If i start a debugging session with to my mac with 
the ios simulator (no matter which device) i get the 
message down below and the app does not get compiled.
If i do that to a locally attaced iphone or even remotely connected
there is no message like that. 
I know that the last sentence is nonsense since the message
already tells us that its about the simulator, but
for completeness i wanted to add that there is a way
where ios works.
This is also a testapp which has no specific code in it, its
just a maui app right created from the template supplied 
with Visual Studio and mtadmob added.

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		clang++ exited with code 1:
ld: warning: object file (/Users/whann/Library/Caches/Xamarin/mtbs/builds/AdmobNetMaui/67a4a38d35498af05c5ff1347ecad9c722dbbb9e3f91d1641cc867ec8202ebd2/C:/Users/hann/AppData/Local/XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator/GoogleMobileAds.framework/GoogleMobileAds(GADGestureMock.o)) was built for newer iOS Simulator version (14.5) than being linked (14.0)

**Comment by whann0205** [comment]
I found myself
<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
    <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
</PropertyGroup>

<PropertyGroup>
    <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
</PropertyGroup>

Does the trick

**Comment by marcojak** [comment]
Hi.
It's written on the read me too how to fix it.
