### ISSUE TITLE
Error build with XCode 14

### ISSUE THREAD

**Issue by banhthanhvi** [marcojak/MauiMTAdmob#9]
After upgrade:
- VS 2022 17.3.6
- XCode 14
Publish to App Store get these errors:
ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/FBLPromises.framework/FBLPromises' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/FirebaseCore.framework/FirebaseCore' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/GoogleAPIClientForREST.framework/GoogleAPIClientForREST' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/GoogleDataTransport.framework/GoogleDataTransport' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/GoogleUtilities.framework/GoogleUtilities' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/Protobuf.framework/Protobuf' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/leveldb.framework/leveldb' contains bitcode.

ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/nanopb.framework/nanopb' contains bitcode.

How can I fix it?
Thank you.

**Comment by changguangyu** [comment]
same error here, how to solve this?

**Comment by marcojak** [comment]
I'm going to have a look and if the problem is with the plugin I'll release a new version asap.

**Comment by changguangyu** [comment]
> I'm going to have a look and if the problem is with the plugin I'll release a new version asap.

Thanks. I used the fix here and it is work.
https://github.com/dotnet/maui/issues/10989

**Comment by marcojak** [comment]
Check if the new version 1.0.2 works fine...I've just published it.

**Comment by marcojak** [comment]
This shouldn't be an issue anymore.
