### ISSUE TITLE
Can't use latest Plugin.InAppBilling because of old xamarin.googleplayservices.ads.Lite

### ISSUE THREAD

**Issue by NGumby** [marcojak/MauiMTAdmob#91]
I get this error when trying to install Plugin.InAppBilling

Version conflict detected for Xamarin.AndroidX.Lifecycle.Runtime. Install/reference Xamarin.AndroidX.Lifecycle.Runtime 2.8.3.1 directly to project CSNativeApp to resolve this issue. 
 CSNativeApp -> Plugin.InAppBilling 8.0.3-beta -> Xamarin.AndroidX.Lifecycle.Runtime (>= 2.8.3.1) 
 CSNativeApp -> Plugin.MauiMTAdmob 1.5.1 -> Xamarin.GooglePlayServices.Ads.Lite 122.3.0.3 -> Xamarin.AndroidX.Work.Runtime 2.9.0 -> Xamarin.AndroidX.Lifecycle.Service 2.6.2.3 -> Xamarin.AndroidX.Lifecycle.Runtime (>= 2.6.2.3 && < 2.6.3).

Any way you could upgrade Xamarin.GooglePlayServices.Ads.Lite to version 123?

**Comment by MoienTajik** [comment]
Same issue with .NET 9 because of transitive dependencies of `Microsoft.Maui.Controls` (`Xamarin.AndroidX.Lifecycle.Runtime`)

**Comment by marcojak** [comment]
I already have a version with version 123.
I was hoping to add more things but, I'll do just a couple of tests and then I'll publish the app.
I'll then do the additional planned changes in a following release.

**Comment by marcojak** [comment]
Version 1.6.0 should be online in the next couple of minutes.
Closing for now.
If there are issues, please open a new issue
