### ISSUE TITLE
UserId in MTRewardedAdOptions not used in LoadRewarded method

### ISSUE THREAD

**Issue by MoienTajik** [marcojak/MauiMTAdmob#93]
Hi,

I’m experiencing an issue with the `LoadRewarded` method when using **Rewarded Ads.** Specifically, I’m passing the `UserId` as part of the `MTRewardedAdOptions` to the `LoadRewarded` method, but it appears that this `UserId` (and the whole `MTRewardedAdOptions` passed argument) is not being used within the `RewardService`.

As a result, my SSV (Server-Side Verification) fails because the `UserId` is empty, despite it being provided at the call site.

**Versions:**
Plugin.MauiMTAdmob: v1.6.0

**Comment by marcojak** [comment]
I'll check and if I find the issue, I'll update the plugin asap.

**Comment by MoienTajik** [comment]
Did you have a chance to take a look at this one? I would be happy to contribute, but since it's not open source, I can't do anything except waiting ...

**Comment by marcojak** [comment]
I'm looking at it right now.
You are right, the options are not passed correctly.
I'm looking at fixing it right now and I'll publish an update asap.

**Comment by marcojak** [comment]
I've just released the new version 1.6.2 that fixes this issue on both Android and iOS.
It should be available in the next few minutes.
I'm closing this issue for now but feel free to open a new one if needed.
