### ISSUE TITLE
Project doesn't build on iOS

### ISSUE THREAD

**Issue by dsancho** [marcojak/MauiMTAdmob#94]
I created a MAUI iOS new project and just added MauiMTAdmob. 

Then can't compile and the error is the following: 2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8020\targets\Xamarin.Shared.Sdk.targets(783,3): error MT7091: File 'C:/Users/dsanc/AppData/Local/XamarinBuildDownloadCache/FAdM-8.13.0/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/GoogleMobileAds' is not a valid framework: Index and count must refer to a location within the buffer.

Using 
MauiMTAdmob version 1.6, 
XCode 15.4, 
Visual Studio 2022 17.11.2 & 17.12.0 Preview 1.0
.net MAUI8.0.80

I think is the same problem as #46

**Comment by marcojak** [comment]
Change the nuget location to something like c:/n/ 

Then clean the solution, remove the bin and obj folders and rebuild it.

It should work then.

**Comment by dsancho** [comment]
Do you mean setting the globalPackagesFolder in the nuget.config file?

**Comment by marcojak** [comment]
Yes, some filepaths are too long for windows and usually settings the nuget
path to n, helps in this case

**Comment by dsancho** [comment]
Solved! The problem was that GoogleMobileAds was corrupted. Have to delete everything under XamarinBuildDownloadCache and rebuild.
