### ISSUE TITLE
AdsLoaded and AdsFailedToLoad are not triggered on iOS

### ISSUE THREAD

**Issue by MerlinTHS** [marcojak/MauiMTAdmob#95]
Hi, we use the MauiMTAdmob plugin 1.6.2 to show ads and need to react (hide or show some other elements) when an ad is either loaded or not. On android everything works fine but on iOS the callbacks we register for MTAdView.AdsLoaded and MTAdView.AdsFailedToLoad are never called.

**Comment by marcojak** [comment]
Let me check

**Comment by marcojak** [comment]
Fixed in version 1.6.3
