### ISSUE TITLE
CrossMauiMTAdmob does not contain a definition for “Init”

### ISSUE THREAD

**Issue by MoritzLe0809** [marcojak/MauiMTAdmob#97]
I have been getting this error since the last update:

Error CS1061: “IMTAdmob” does not contain a definition for “Init”, and no accessible init extension method could be found that accepts an initial argument of type “IMTAdmob” (possibly missing a using directive or assembly reference)

It only occurs for initialization on iOS.

Example:
string license = ""; //<-- Your license key here
                    string deviceId = ""; //<--- Your test device id here
                    string OPENADS_AD_UNIT_ID = "";
                    string NATIVEADS_AD_UNIT_ID = _premiumSettingsRepository.BANNERID;
                    bool areOpenAdsEnabled = false;
                    bool initialiseConsentAtStartup = false;
                    //If you have a license code:      
                    CrossMauiMTAdmob.Current.Init(license, NATIVEADS_AD_UNIT_ID, OPENADS_AD_UNIT_ID, areOpenAdsEnabled, false, deviceId, Plugin.MauiMTAdmob.Extra.DebugGeography.DEBUG_GEOGRAPHY_EEA, initialiseConsentAtStartup);

**Comment by MerlinTHS** [comment]
You may need to update your MAUI workloads.

**Comment by MoritzLe0809** [comment]
Thank you, that's it.

I updated Maui Workload from 8.0.300 to 8.0.400. Now it's work.
