### ISSUE TITLE
Cannot call CrossMauiMTAdmob.Current.Init since 1.6.1 in IOS

### ISSUE THREAD

**Issue by tienbrown** [marcojak/MauiMTAdmob#98]
Receiving following message since version 1.6.1 when trying to initialiaze in iOS AppDelegate. Using Visual Studio Code, .NET 8, and maui.

'IMTAdmob' does not contain a definition for 'Init' and no accessible extension method 'Init' accepting a first argument of type 'IMTAdmob' could be found (are you missing a using directive or an assembly reference?)

**Comment by marcojak** [comment]
Check here: https://github.com/marcojak/MauiMTAdmob/issues/97

You need to update the MAUI workload and then it will work.

**Comment by tienbrown** [comment]
Thanks, that fixed it.
